DROP TABLE SWING_MEMBER;
CREATE TABLE SWING_MEMBER(
     SWNUM  VARCHAR2(20)PRIMARY KEY 
    ,SWNAME VARCHAR2(20) NOT NULL
    ,SWID   VARCHAR2(20)
    ,SWPW   VARCHAR2(20) NOT NULL   
    ,DELETEYN VARCHAR2(1) NOT NULL
    ,INSERTDATE DATE
    ,UPDATEDATE DATE
);  

-- SYS_C0011097
SELECT  TABLE_NAME, INDEX_NAME, COLUMN_NAME
FROM    USER_IND_COLUMNS
WHERE   TABLE_NAME IN ('SWING_MEMBER');

SELECT  /*+ INDEX_DESC(SYS_C0011097)*/											
        NVL(MAX(SUBSTR(A.SWNUM, -4)), 0) + 1 COMMNO	
FROM    SWING_MEMBER A;							